// 图片风格配置 - SEO优化版本
// 每个风格包含: id, name(中文), nameEn(英文), prompt(提示词), category(分类)

export interface Style {
  id: string;
  name: string;
  nameEn: string;
  prompt: string;
  category: 'hot' | '3d' | 'cartoon' | 'anime' | 'art' | 'life' | 'avatar';
  example: string;
  keywords: string[];
  aspectRatio?: '1:1' | '3:2' | '2:3';
}

export const styleCategories = {
  hot: { name: '热门', nameEn: 'Hot' },
  '3d': { name: '3D风格', nameEn: '3D Style' },
  cartoon: { name: '卡通风格', nameEn: 'Cartoon' },
  anime: { name: '动漫风格', nameEn: 'Anime' },
  art: { name: '艺术风格', nameEn: 'Art Style' },
  life: { name: '生活风格', nameEn: 'Life Style' },
  avatar: { name: '头像风格', nameEn: 'Avatar' },
};

export const styles: Style[] = [
  // ==================== 热门风格 ====================
  {
    id: 'ghibli',
    name: '吉卜力',
    nameEn: 'Ghibli Style',
    prompt: '吉卜力工作室动画风格，手绘感，细腻色彩，自然场景，宫崎骏风格，梦幻氛围，温暖色调，魔法公主，幽灵公主，千与千寻',
    category: 'hot',
    example: 'https://picsum.photos/seed/ghibli/512/512',
    keywords: ['吉卜力风格', '宫崎骏风格', '动漫风', '手绘动漫', '日本动画'],
    aspectRatio: '1:1',
  },
  {
    id: 'selfie',
    name: '随意自拍',
    nameEn: 'Casual Selfie',
    prompt: '随意自拍风格，自然表情，日常生活场景，真实感人像，温暖光线，随性自然，街头风格，都市生活',
    category: 'hot',
    example: 'https://picsum.photos/seed/selfie/512/512',
    keywords: ['自拍风格', '生活照', '日常照片', '自然风格'],
    aspectRatio: '3:2',
  },
  {
    id: 'old-photo',
    name: '老照片',
    nameEn: 'Vintage Photo',
    prompt: '复古老照片风格，泛黄色调，胶片颗粒感，60年代摄影风格，褪色效果，怀旧氛围，老式相框，历史感',
    category: 'hot',
    example: 'https://picsum.photos/seed/vintage/512/512',
    keywords: ['老照片风格', '复古照片', '怀旧照片', '胶片风', '复古滤镜'],
    aspectRatio: '3:2',
  },
  {
    id: 'figure-photo',
    name: '手办照片',
    nameEn: 'Figure Photo',
    prompt: '精细手办模型风格，塑料质感，柔和阴影，真实比例，工业设计感，精细细节，收藏级手办，展示柜背景',
    category: 'hot',
    example: 'https://picsum.photos/seed/figure/512/512',
    keywords: ['手办照片', '模型照片', 'PVC figurine', '二次元手办'],
    aspectRatio: '1:1',
  },
  {
    id: 'q-version',
    name: 'Q版摆件',
    nameEn: 'Q-Mini Figure',
    prompt: 'Q版人物摆件风格，大头娃娃，圆润可爱，萌系，奶油风格，柔和色调，治愈系，迷你小人偶',
    category: 'hot',
    example: 'https://picsum.photos/seed/qmini/512/512',
    keywords: ['Q版摆件', 'Q版人偶', 'mini figure', '可爱摆件', '治愈风'],
    aspectRatio: '1:1',
  },
  {
    id: 'pixar-3d',
    name: '皮克斯3D',
    nameEn: 'Pixar 3D Style',
    prompt: '皮克斯Pixar 3D动画风格，圆润角色模型，鲜艳色彩，电影光照，感人故事氛围，CG动画，皮克斯角色设计',
    category: 'hot',
    example: 'https://picsum.photos/seed/pixar/512/512',
    keywords: ['皮克斯风格', 'Pixar风格', '3D动画风', '迪士尼3D', 'CG动画'],
    aspectRatio: '3:2',
  },
  {
    id: 'japan-figure',
    name: '日系手办',
    nameEn: 'Japanese Figure',
    prompt: '日系手办风格，二次元，动漫周边精美手办，精致细节，动态姿势，喷涂上色，专业涂装，收藏展示',
    category: 'hot',
    example: 'https://picsum.photos/seed/japanfigure/512/512',
    keywords: ['日系手办', '日本手办', '二次元手办', 'anime figure', '动漫周边'],
    aspectRatio: '1:1',
  },
  {
    id: 'lego',
    name: 'LEGO',
    nameEn: 'LEGO Style',
    prompt: '乐高LEGO积木风格，塑料质感，鲜艳颜色，密集颗粒感，经典乐高小人，积木拼接，创意无限',
    category: 'hot',
    example: 'https://picsum.photos/seed/lego/512/512',
    keywords: ['乐高风格', 'LEGO风', '积木风格', '玩具风', '乐高小人'],
    aspectRatio: '1:1',
  },
  {
    id: '3d-q-version',
    name: '3D Q版',
    nameEn: '3D Q-Version',
    prompt: '3D Q版人物风格，超可爱，圆润3D模型，柔和渲染，梦幻色彩，泡泡玛特风格，盲盒手感，精致可爱',
    category: 'hot',
    example: 'https://picsum.photos/seed/3dq/512/512',
    keywords: ['3D Q版', 'Q版3D', '泡泡玛特风', '盲盒风', '可爱3D'],
    aspectRatio: '1:1',
  },
  {
    id: 'simpson',
    name: '辛普森一家',
    nameEn: 'The Simpsons',
    prompt: '辛普森一家动画风格，黄色皮肤，简洁线条，美国卡通，幽默夸张，辛普森家族，明亮色彩，经典卡通',
    category: 'hot',
    example: 'https://picsum.photos/seed/simpsons/512/512',
    keywords: ['辛普森风格', 'Simpsons风', '美式卡通', '黄色小人', '家庭卡通'],
    aspectRatio: '3:2',
  },
  {
    id: 'banana-art',
    name: '香蕉艺术',
    nameEn: 'Banana Art',
    prompt: '香蕉艺术风格，水果创意，香蕉元素，超现实主义，创意摄影，趣味性，艺术感，色彩鲜艳，概念艺术',
    category: 'hot',
    example: 'https://picsum.photos/seed/banana/512/512',
    keywords: ['香蕉艺术', '水果创意', '趣味摄影', '创意艺术'],
    aspectRatio: '1:1',
  },
  {
    id: 'card-blast',
    name: '炸裂卡牌',
    nameEn: 'Blast Card',
    prompt: '炸裂卡牌风格，游戏王风格，集换式卡牌，闪卡效果，炫酷特效，战斗卡，魔法卡，游戏卡片收藏',
    category: 'hot',
    example: 'https://picsum.photos/seed/cardblast/512/512',
    keywords: ['卡牌风格', '游戏王', '集换式卡牌', 'TCG', '卡牌收藏'],
    aspectRatio: '2:3',
  },
  {
    id: 'inflatables',
    name: '充气玩具',
    nameEn: 'Inflatable Toys',
    prompt: '充气玩具风格，塑料充气效果，膨胀圆润，泳池玩具，水上玩具，明亮色彩，PVC材质质感，趣味可爱',
    category: 'hot',
    example: 'https://picsum.photos/seed/inflatable/512/512',
    keywords: ['充气玩具', '水上玩具', '泳池玩具', 'PVC玩具'],
    aspectRatio: '1:1',
  },
  {
    id: 'enamel-pin',
    name: '琺瑯针',
    nameEn: 'Enamel Pin',
    prompt: '珐琅徽章针风格，金属质感，精致小徽章，彩色图案，别针徽章，文创周边，纪念章，金属工艺',
    category: 'hot',
    example: 'https://picsum.photos/seed/enamelpin/512/512',
    keywords: ['珐琅徽章', '别针徽章', '文创周边', '纪念章'],
    aspectRatio: '1:1',
  },
  {
    id: 'retro-light',
    name: '复古光影',
    nameEn: 'Retro Light',
    prompt: '复古光影风格，老式影棚，布朗尼相机，Lomo风格，暗角漏光，怀旧色调，胶片感，时光感',
    category: 'hot',
    example: 'https://picsum.photos/seed/retrolight/512/512',
    keywords: ['复古光影', '胶片风', 'LOMO风', '怀旧色调', '老照片质感'],
    aspectRatio: '3:2',
  },
  {
    id: 'out-of-screen',
    name: '走出屏幕-卡通',
    nameEn: 'Out of Screen Cartoon',
    prompt: '走出屏幕卡通风格，动漫人物从屏幕中跳出来，次元壁打破，二次元转三次元，创意合成，跨界融合',
    category: 'hot',
    example: 'https://picsum.photos/seed/outcreen/512/512',
    keywords: ['走出屏幕', '次元壁', '二次元转三次元', '创意合成'],
    aspectRatio: '3:2',
  },
  {
    id: 'png-sticker',
    name: 'png格式表情',
    nameEn: 'PNG Sticker',
    prompt: 'PNG格式表情包风格，透明背景，可爱表情，聊天表情包，动态贴纸，趣味表情，社交软件表情',
    category: 'hot',
    example: 'https://picsum.photos/seed/pngsticker/512/512',
    keywords: ['表情包', 'PNG素材', '贴纸风', '聊天表情'],
    aspectRatio: '1:1',
  },
  {
    id: 'candy-portrait',
    name: '糖果肖像',
    nameEn: 'Candy Portrait',
    prompt: '糖果肖像风格，色彩缤纷，糖果色系，马卡龙色调，梦幻甜美，少女系，柔和渐变，甜品色调',
    category: 'hot',
    example: 'https://picsum.photos/seed/candy/512/512',
    keywords: ['糖果风', '马卡龙色', '甜美风格', '少女风', '梦幻色调'],
    aspectRatio: '1:1',
  },
  {
    id: 'cartoon-namecard',
    name: '卡通名片',
    nameEn: 'Cartoon Namecard',
    prompt: '卡通名片风格，动漫人物形象，个性化头像，专业又不失趣味，商业与创意结合，职场头像，社交名片',
    category: 'hot',
    example: 'https://picsum.photos/seed/cartoonname/512/512',
    keywords: ['卡通名片', '动漫头像', '创意名片', '个性头像'],
    aspectRatio: '3:2',
  },
  {
    id: 'dbz-style',
    name: '龙珠风格',
    nameEn: 'Dragon Ball Style',
    prompt: '龙珠动漫风格，日本经典热血动漫，赛亚人，超级赛亚人，战斗力爆发，经典台词动感，气氛热烈',
    category: 'hot',
    example: 'https://picsum.photos/seed/dbz/512/512',
    keywords: ['龙珠风格', '七龙珠', '赛亚人', '日本动漫', '热血动漫'],
    aspectRatio: '3:2',
  },
  {
    id: 'retro-animation',
    name: '复古动画',
    nameEn: 'Retro Animation',
    prompt: '复古动画风格，80年代日本OVA动画，老动画质感，经典怀旧，赛璐珞上色，OVA风格，童年回忆',
    category: 'hot',
    example: 'https://picsum.photos/seed/retroanime/512/512',
    keywords: ['复古动画', '80年代动画', 'OVA风格', '怀旧动漫'],
    aspectRatio: '3:2',
  },
  {
    id: 'code-namecard',
    name: '代码名片',
    nameEn: 'Code Namecard',
    prompt: '代码名片风格，程序员专属，代码元素，键盘敲击，IT工程师，程序员文化，代码艺术，科技感',
    category: 'hot',
    example: 'https://picsum.photos/seed/codecard/512/512',
    keywords: ['程序员名片', '代码风', 'IT头像', '开发者风格', 'coding'],
    aspectRatio: '3:2',
  },
  {
    id: 'keychain',
    name: '钥匙扣',
    nameEn: 'Keychain Style',
    prompt: '钥匙扣风格，立体小挂件，金属钥匙扣，个性吊坠，可爱钥匙圈，精致配件，随身携带',
    category: 'hot',
    example: 'https://picsum.photos/seed/keychain/512/512',
    keywords: ['钥匙扣风格', '吊坠风', '个性配件', '可爱挂件'],
    aspectRatio: '1:1',
  },
  {
    id: 'polaroid',
    name: '拍立得',
    nameEn: 'Polaroid Photo',
    prompt: '拍立得照片风格，即时成像，白边相框，甜美瞬间，即影即有，旅行记录，生活仪式感，文艺小清新',
    category: 'hot',
    example: 'https://picsum.photos/seed/polaroid/512/512',
    keywords: ['拍立得', '即时成像', '白边相片', '文艺照片'],
    aspectRatio: '1:1',
  },
  {
    id: 'couple-box',
    name: '情侣盒',
    nameEn: 'Couple Box',
    prompt: '情侣礼盒风格，成对出现的礼物，浪漫情侣装，成双成对，甜蜜爱情，恋爱氛围，情侣周边',
    category: 'hot',
    example: 'https://picsum.photos/seed/couplebox/512/512',
    keywords: ['情侣风格', '恋爱风', '甜蜜照片', '情侣周边'],
    aspectRatio: '1:1',
  },
  {
    id: 'tortoise-immortal',
    name: '龟仙人',
    nameEn: 'Tortoise Immortal',
    prompt: '龟仙人风格，龙珠角色，肌肉老爷爷，武道服，龟派气功，经典角色，七龙珠，孙悟空师父',
    category: 'hot',
    example: 'https://picsum.photos/seed/tortoise/512/512',
    keywords: ['龟仙人', '龙珠角色', '武天老师', '经典动漫角色'],
    aspectRatio: '3:2',
  },
  {
    id: '3d-keychain',
    name: '3D钥匙扣',
    nameEn: '3D Keychain',
    prompt: '3D立体钥匙扣，树脂钥匙扣，立体小人，个性挂件，精致工艺，细节丰富，立体浮雕效果',
    category: 'hot',
    example: 'https://picsum.photos/seed/3dkeychain/512/512',
    keywords: ['3D钥匙扣', '立体挂件', '树脂钥匙扣', '个性吊坠'],
    aspectRatio: '1:1',
  },
  {
    id: '3d-illustration',
    name: '3D插图',
    nameEn: '3D Illustration',
    prompt: '3D插画风格，立体感插图，现代插画，3D渲染效果，创意设计，商业插画，质感丰富，时尚插画',
    category: 'hot',
    example: 'https://picsum.photos/seed/3dillustration/512/512',
    keywords: ['3D插画', '立体插画', '商业插画', '现代插画'],
    aspectRatio: '3:2',
  },
  {
    id: 'snoopy',
    name: 'Snoopy',
    nameEn: 'Snoopy Style',
    prompt: '史努比Snoopy风格，可爱卡通犬，温馨家庭漫画，查理布朗的宠物，幻想狗，人物造型，经典卡通',
    category: 'hot',
    example: 'https://picsum.photos/seed/snoopy/512/512',
    keywords: ['史努比', 'Snoopy', '卡通狗', '花生漫画'],
    aspectRatio: '1:1',
  },
  {
    id: 'gta-poster',
    name: 'GTA海报',
    nameEn: 'GTA Poster Style',
    prompt: 'GTA游戏风格，侠盗猎车手，街头风格，潮流元素，城市冒险，写实渲染，游戏海报，都市犯罪',
    category: 'hot',
    example: 'https://picsum.photos/seed/gtaposter/512/512',
    keywords: ['GTA风格', '侠盗猎车手', '游戏海报', '街头风'],
    aspectRatio: '2:3',
  },
  {
    id: 'clay-style',
    name: '粘土风格',
    nameEn: 'Clay Style',
    prompt: '粘土动画风格，定格动画，修片处理，3D捏塑效果，手工质感，作品集，微缩场景，艺术创作',
    category: 'hot',
    example: 'https://picsum.photos/seed/clay/512/512',
    keywords: ['粘土风格', '定格动画', '手工质感', '微缩场景'],
    aspectRatio: '1:1',
  },
  {
    id: 'first-person',
    name: '第一视角',
    nameEn: 'First Person View',
    prompt: '第一视角风格，游戏视角代入，主观镜头，玩家视角，身临其境，沉浸式体验，POV视角',
    category: 'hot',
    example: 'https://picsum.photos/seed/firstperson/512/512',
    keywords: ['第一视角', 'POV视角', '主观镜头', '游戏视角'],
    aspectRatio: '3:2',
  },
  {
    id: 'digimon',
    name: '数码宝贝风',
    nameEn: 'Digimon Style',
    prompt: '数码宝贝风格，日本经典动画，数码宝贝，暴龙改造，电子世界，冒险精神，进化光芒，热血冒险',
    category: 'hot',
    example: 'https://picsum.photos/seed/digimon/512/512',
    keywords: ['数码宝贝', '数码暴龙', '日本动画', '冒险动漫'],
    aspectRatio: '3:2',
  },
  {
    id: 'q-propose',
    name: 'Q版求婚场景',
    nameEn: 'Q Version Proposal',
    prompt: 'Q版求婚场景，卡通风格，浪漫求婚，戒指，求婚惊喜，甜蜜瞬间，恋人故事，浪漫情节',
    category: 'hot',
    example: 'https://picsum.photos/seed/qpropose/512/512',
    keywords: ['求婚风格', '浪漫照片', 'Q版场景', '甜蜜恋人'],
    aspectRatio: '1:1',
  },
  {
    id: '3d-frame',
    name: '立体相框',
    nameEn: '3D Photo Frame',
    prompt: '立体相框风格，3D立体效果，层次感强，深度感，浮雕效果，装饰画，立体照片框，艺术相框',
    category: 'hot',
    example: 'https://picsum.photos/seed/3dframe/512/512',
    keywords: ['立体相框', '3D相框', '浮雕效果', '装饰画'],
    aspectRatio: '1:1',
  },
  {
    id: 'chinese-wedding',
    name: '中式婚礼',
    nameEn: 'Chinese Wedding',
    prompt: '中式婚礼风格，中国传统婚礼，红色喜庆，凤冠霞帔，传统嫁衣，喜庆氛围，中式婚纱照，中国文化',
    category: 'hot',
    example: 'https://picsum.photos/seed/chinesewedding/512/512',
    keywords: ['中式婚礼', '传统婚纱', '中国风', '红色喜庆', '秀禾服'],
    aspectRatio: '3:2',
  },
  {
    id: 'room-design',
    name: '房间设计',
    nameEn: 'Room Design',
    prompt: '房间设计风格，室内设计效果图，家居装饰，空间设计，美化梦想，室内设计，样板间，家装效果图',
    category: 'hot',
    example: 'https://picsum.photos/seed/roomdesign/512/512',
    keywords: ['房间设计', '室内设计', '家居装饰', '装修效果图'],
    aspectRatio: '3:2',
  },
  {
    id: 'lego-single',
    name: '乐高收藏品',
    nameEn: 'LEGO Collectible',
    prompt: '乐高收藏品风格，单个人物手办，精致细节，乐高小人，收藏展示，颗粒感，经典IP，可动人偶',
    category: 'hot',
    example: 'https://picsum.photos/seed/legosingle/512/512',
    keywords: ['乐高收藏', '乐高手办', '乐高人偶', 'LEGO collectible'],
    aspectRatio: '1:1',
  },
  {
    id: 'role-crossover',
    name: '角色穿越',
    nameEn: 'Role Crossover',
    prompt: '角色穿越风格，动漫角色进入现实世界，次元壁打破，跨界组合，创意的二次元结合，现实与幻想',
    category: 'hot',
    example: 'https://picsum.photos/seed/rolecrossover/512/512',
    keywords: ['角色穿越', '次元壁打破', '跨界组合', '二次元混合'],
    aspectRatio: '3:2',
  },
  {
    id: 'onepiece-figure',
    name: '海贼王手办',
    nameEn: 'One Piece Figure',
    prompt: '海贼王手办风格，海贼王航海王动漫周边，路飞索隆妮可罗宾，精致手办模玩，手办拍摄，展示陈列',
    category: 'hot',
    example: 'https://picsum.photos/seed/onepiece/512/512',
    keywords: ['海贼王手办', '航海王手办', '路飞船长', '动漫周边手办'],
    aspectRatio: '1:1',
  },
  {
    id: 'satire-poster',
    name: '讽刺海报',
    nameEn: 'Satire Poster',
    prompt: '讽刺漫画海报风格，幽默讽刺，社会评论，搞怪创意，波普艺术讽刺，政治漫画，创意海报设计',
    category: 'hot',
    example: 'https://picsum.photos/seed/satire/512/512',
    keywords: ['讽刺海报', '讽刺漫画', '幽默设计', '创意海报'],
    aspectRatio: '2:3',
  },
  {
    id: 'four-panel',
    name: '四格漫画',
    nameEn: 'Four Panel Comic',
    prompt: '四格漫画风格，连环漫画分格，故事性强，幽默短篇，日漫风格，分镜设计，漫画分格，情节连贯',
    category: 'hot',
    example: 'https://picsum.photos/seed/fourpanel/512/512',
    keywords: ['四格漫画', '连环漫画', '漫画分镜', '日漫风格'],
    aspectRatio: '1:1',
  },
  {
    id: 'ink-painting',
    name: '水墨画',
    nameEn: 'Ink Painting',
    prompt: '中国水墨画风格，传统国画，禅意山水，毛笔书法，黑白灰调，古典意境，文人画，水墨晕染',
    category: 'art',
    example: 'https://picsum.photos/seed/inkpaint/512/512',
    keywords: ['水墨画', '中国画', '国画风格', '传统艺术', '禅意山水'],
    aspectRatio: '3:2',
  },
  {
    id: 'titanic',
    name: '泰坦尼克号',
    nameEn: 'Titanic Style',
    prompt: '泰坦尼克号电影风格，经典电影场景，杰克与露丝，沉船爱情，世纪爱情，大海背景，浪漫离别',
    category: 'hot',
    example: 'https://picsum.photos/seed/titanic/512/512',
    keywords: ['泰坦尼克号', '经典电影', '杰克露丝', '浪漫爱情'],
    aspectRatio: '3:2',
  },
  {
    id: 'funkopop',
    name: 'Funkopop公仔',
    nameEn: 'Funkopop Style',
    prompt: 'Funko Pop公仔风格，大眼睛卡通公仔，方头设计，潮流玩具，收藏级PVC，Vinyl Collectible，流行文化',
    category: 'hot',
    example: 'https://picsum.photos/seed/funkopop/512/512',
    keywords: ['Funko Pop', '潮流公仔', 'POP公仔', 'Vinyl玩具'],
    aspectRatio: '1:1',
  },
  {
    id: 'flat-sticker',
    name: '扁平贴纸',
    nameEn: 'Flat Sticker',
    prompt: '扁平化贴纸风格，简约设计，无透视，纯色块，简洁图形，图标风格，扁平插画，社交头像',
    category: 'avatar',
    example: 'https://picsum.photos/seed/flatsticker/512/512',
    keywords: ['扁平贴纸', '简约风格', '纯色块', '图标风格'],
    aspectRatio: '1:1',
  },
  {
    id: 'ootd',
    name: 'OOTD穿搭',
    nameEn: 'OOTD Style',
    prompt: 'OOTD今日穿搭风格，时尚街拍，服装展示，时尚博主，潮流穿搭，每日穿搭分享，时尚摄影',
    category: 'life',
    example: 'https://picsum.photos/seed/ootd/512/512',
    keywords: ['OOTD穿搭', '时尚街拍', '每日穿搭', '潮流时尚'],
    aspectRatio: '3:2',
  },
  {
    id: 'family-portrait',
    name: '全家福',
    nameEn: 'Family Portrait',
    prompt: '全家福风格，家庭合照，亲情温暖，幸福时光，节日团聚，家庭照片，温馨氛围，成长的记录',
    category: 'life',
    example: 'https://picsum.photos/seed/familyp/512/512',
    keywords: ['全家福', '家庭合照', '亲情照片', '温馨家庭'],
    aspectRatio: '3:2',
  },
  {
    id: 'couple-crystal',
    name: '情侣水晶',
    nameEn: 'Couple Crystal',
    prompt: '情侣水晶内雕风格，3D水晶内雕，透明水晶，纪念礼物，透明立体，情侣纪念，定制礼品',
    category: 'hot',
    example: 'https://picsum.photos/seed/couplecrystal/512/512',
    keywords: ['水晶内雕', '情侣水晶', '3D雕刻', '纪念礼品'],
    aspectRatio: '1:1',
  },
  {
    id: 'matryoshka',
    name: '套娃',
    nameEn: 'Matryoshka Doll',
    prompt: '俄罗斯套娃风格，层层叠加，浓郁民族风，彩色图案，传统工艺品，波兰套娃，木制玩具，民俗艺术',
    category: 'art',
    example: 'https://picsum.photos/seed/matryoshka/512/512',
    keywords: ['套娃', '俄罗斯套娃', '民族风格', '传统工艺'],
    aspectRatio: '2:3',
  },
  {
    id: 'line-illustration',
    name: '线条插画',
    nameEn: 'Line Illustration',
    prompt: '线条插画风格，简洁线条，单色线条，轮廓插画，线稿艺术，简约艺术，纯线条，单色插画',
    category: 'art',
    example: 'https://picsum.photos/seed/lineart/512/512',
    keywords: ['线条插画', '线稿风格', '轮廓画', '简约线条'],
    aspectRatio: '1:1',
  },
  {
    id: 'pixel-cross',
    name: '像素十字绣',
    nameEn: 'Pixel Cross-stitch',
    prompt: '像素十字绣风格，十字绣刺绣，像素艺术，DIY刺绣，手工艺术，绣花图案，复古刺绣，工艺品',
    category: 'art',
    example: 'https://picsum.photos/seed/pixelcross/512/512',
    keywords: ['十字绣风格', '像素刺绣', 'DIY刺绣', '手工艺术'],
    aspectRatio: '1:1',
  },
  {
    id: 'role-card',
    name: '角色卡片',
    nameEn: 'Role Card',
    prompt: '角色卡片风格，游戏角色卡，SSR卡面，炫酷特效，游戏立绘，角色展示，卡牌设计，游戏周边',
    category: 'avatar',
    example: 'https://picsum.photos/seed/rolecard/512/512',
    keywords: ['角色卡片', '游戏立绘', '卡牌设计', 'SSR卡面'],
    aspectRatio: '2:3',
  },
  // ==================== 卡通/动漫风格 ====================
  { 
    id: 'cute-cartoon', 
    name: '可爱卡通',
    nameEn: 'Cute Cartoon',
    prompt: '可爱卡通风格，Q版，大眼睛，色彩鲜艳，圆润线条，萌系，卡通形象，儿童插画',
    category: 'cartoon',
    example: 'https://picsum.photos/seed/cutecartoon/512/512',
    keywords: ['可爱卡通', 'Q版', '萌系', '卡通风格'],
    aspectRatio: '1:1',
  },
  { 
    id: 'anime-manga', 
    name: '动漫漫画',
    nameEn: 'Anime Manga',
    prompt: '动漫漫画风格，日本漫画风格，大眼睛，清晰线条，色彩鲜明，二次元，日系漫画，少年漫画',
    category: 'anime',
    example: 'https://picsum.photos/seed/animemanga/512/512',
    keywords: ['动漫风格', '日漫', '二次元', '日本漫画'],
    aspectRatio: '3:2',
  },
  { 
    id: 'comic-book', 
    name: '漫画书',
    nameEn: 'Comic Book',
    prompt: '漫画书风格，美国漫画风格，DC/Marvel美式漫画，大胆线条，鲜明色彩，超级英雄，漫画网点',
    category: 'cartoon',
    example: 'https://picsum.photos/seed/comicbook/512/512',
    keywords: ['美式漫画', '漫画书', '超级英雄', 'DC漫画', 'Marvel漫画'],
    aspectRatio: '3:2',
  },
  { 
    id: 'disney', 
    name: '迪士尼',
    nameEn: 'Disney Style',
    prompt: '迪士尼动画风格，经典迪士尼，圆润造型，明亮色彩，童话故事，梦幻氛围，迪士尼公主，王子',
    category: 'cartoon',
    example: 'https://picsum.photos/seed/disney/512/512',
    keywords: ['迪士尼风格', 'Disney风', '童话风格', '公主风'],
    aspectRatio: '3:2',
  },
  { 
    id: 'pop-art', 
    name: '波普艺术',
    nameEn: 'Pop Art',
    prompt: '波普艺术风格，安迪沃霍尔风格，鲜艳色彩，重复图案，流行文化元素，漫画网点，大众艺术',
    category: 'art',
    example: 'https://picsum.photos/seed/popart/512/512',
    keywords: ['波普艺术', 'Pop Art', '安迪沃霍尔', '大众艺术'],
    aspectRatio: '1:1',
  },
  { 
    id: 'stop-motion', 
    name: '定格动画',
    nameEn: 'Stop Motion',
    prompt: '定格动画风格，黏土动画，布偶动画，逐帧拍摄，手工制作感，温暖色调，立体效果',
    category: 'cartoon',
    example: 'https://picsum.photos/seed/stopmotion/512/512',
    keywords: ['定格动画', '黏土动画', '木偶动画', '逐帧动画'],
    aspectRatio: '3:2',
  },
  // ==================== 艺术风格 ====================
  { 
    id: 'pixel-art', 
    name: '像素艺术',
    nameEn: 'Pixel Art',
    prompt: '像素艺术风格，8位或16位游戏风格，块状像素，复古游戏，FC游戏风格，8bit艺术，像素游戏',
    category: 'art',
    example: 'https://picsum.photos/seed/pixelart/512/512',
    keywords: ['像素风格', '像素画', '8bit', '复古游戏风'],
    aspectRatio: '1:1',
  },
  { 
    id: 'chibi', 
    name: 'Q版人物',
    nameEn: 'Chibi Character',
    prompt: 'Q版人物风格，头大身体小，全身人物立绘，Q版角色，游戏Q版，萌系立绘，卡通人物',
    category: 'avatar',
    example: 'https://picsum.photos/seed/chibi/512/512',
    keywords: ['Q版人物', '大头娃娃', 'Q版立绘', '萌系人物'],
    aspectRatio: '2:3',
  },
  // ==================== 自定义 ====================
  {
    id: 'custom-style',
    name: '自定义',
    nameEn: 'Custom Style',
    prompt: '',
    category: 'hot',
    example: 'https://picsum.photos/seed/custom/512/512',
    keywords: ['自定义风格', '自定义提示词', '用户自定义'],
    aspectRatio: '1:1',
  },
];

// 尺寸选项
export const aspectRatios = [
  { id: '3:2', name: '横版', nameEn: 'Landscape', icon: '📐', ratio: '3/2' },
  { id: '1:1', name: '方形', nameEn: 'Square', icon: '⬜', ratio: '1/1' },
  { id: '2:3', name: '竖版', nameEn: 'Portrait', icon: '📏', ratio: '2/3' },
];

// 获取SEO友好的风格描述
export function getStyleSEODescription(style: Style): string {
  return `${style.name}（${style.nameEn}）- ${style.prompt.slice(0, 50)}...`;
}

// 生成图片SEO名称
export function generateImageFilename(styleName: string, styleId: string): string {
  const timestamp = Date.now();
  const sanitizedName = styleName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]/g, '-');
  return `imgart-${sanitizedName}-${styleId}-${timestamp}.jpg`;
}
